# Expected Payment.  Can be more than one options.
payments:
  - amount: 1000
    token: TWT
    address: bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098
  - amount: 0.5
    token: BNB
    address: bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098
# Message templates
message:
    initial: |
        In order to compensate for the efforts of adding a new asset, we kindly ask for a contribution.
        Please pay 1000 TWT to the address below (don't forget to set the *memo*!).
        Trust Wallet Token is distributed to new users through the Referral program, see [TWT Referral Program](https://community.trustwallet.com/t/invite-a-friend-earn-trust-wallet-token-twt/4125)
        Alternatively, BNB is accepted as well.
        The team may waive the fee when justified.
        \nPlease pay:
        $PAY_PARAMS
    notReceived: Fee has not been received yet in full.\n\n$TX_LIST
    received: Fee payment received, thanks! \n\n$PAID_AMOUNT $PAID_CURRENCY\n\n$TX_LIST
    reviewed: Review is not needed any more, no more fee required.
