# Expected Payment.  Can be more than one options.
payments:
  - amount: 1000
    token: TWT
    address: bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098
  - amount: 0.5
    token: BNB
    address: bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098
# Message templates
message:
    initial: |
        Hi! In order to compensate for the efforts of processing PRs, we kindly ask for a contribution.
        See the [Pull Request Fee FAQ](https://developer.trustwallet.com/add_new_asset/pr-fee).
        \nPlease pay  **$PAY1_AMOUNT $PAY1_CURRENCY**  with the memo **$PAY1_MEMO**  to the address `$PAY1_ADDRESS`.
        Alternatively, 0.5 BNB is also accepted (same memo & address).
        \n$QR1_SIMPLE
        \n*Notes*:
        * Trust Wallet Tokens (TWT) are distributed to new users through our [Referral Program](https://community.trustwallet.com/t/invite-a-friend-earn-trust-wallet-token-twt/4125).
        * Payment evaluation happens when there is activity on the PR -- write a comment if you have performed the payment.
        * When payment is detected, an Accept Review is automatically placed on the PR, which is a condition for merge.  The merge is still done manually.
    notReceived: Fee has not been received yet in full.\n\n$TX_LIST
    received: Fee payment received, thanks! \n\n$PAID_AMOUNT $PAID_CURRENCY\n\n$TX_LIST
    reviewed: Review is not needed any more, no more fee required.
