name: Fixes Dryrun
on:
    push:
      branches:
        - '*'
        - '!master'
    pull_request:
      branches: [master]
jobs:
  fix-consistency:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-node@v1
       with:
         node-version: 12
     - name: Install Dependencies
       run: npm ci
     - name: Run fix scripts
       run: |
         npm run resize
         npm run format:all
         npm run gen:list
     - name: Show git status (diff)
       run: git status
     - name: Run test
       run: npm t
