name: Fixes and Consistency Updates
on:
  push:
    branches: [ master ]
jobs:
  scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install Dependencies
        run: npm ci
      - name: Run fix script
        run: npm run fix
      - name: Show fix result (diff); run 'npm run fix' locally
        if: success()
        run: git status
      - name: Run test
        run: npm t
      - name: Commit changes if any
        if: success()
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_user_name: trust-wallet-merge-bot
          commit_user_email: mergebot@trustwallet.com
          commit_message: Fixes and Consistency Updates
